creating the landing page
FACN3/rikaz pull request #19
Opened 2018-02-12 09:27 UTC by hasansaad1

implementing the react router and creating the initial landing page.
reference #18

2018-02-12 10:30 UTC, matthewdking commented
@hasansaad1 assign me when @prodionov and @ghassanmas go through and approve the pr not before :wink:

2018-02-12 12:11 UTC, matthewdking requested changes
remove the bundle from this PR

2018-02-12 12:21 UTC, matthewdking requested changes
`npm run dev` gives me an error:

```
ERROR in ./src/components/ListButtons.js
Module build failed: SyntaxError: super() outside of class constructor (5:4)

  3 | class ListButtons extends React.Component {
  4 |   Constructor(props) {
> 5 |     super(props);
    |     ^
  6 |     this.state = {
  7 |       list: 0,
  8 |       lists: [
```

2018-02-12 12:21 UTC, matthewdking commented on public/main.css
> +.div-introduction{
Naming conventions for CSS. Later on you might have other divs that have introductions which would be confusing. Pick some sort of CSS naming convention now to avoid confusion later.

2018-02-12 12:21 UTC, matthewdking commented on public/main.css
> +  padding: 30px;
please don't use `px` it isn't responsive

2018-02-12 12:21 UTC, matthewdking commented on public/main.css
> +.container{
same as above with the naming :point_up:

2018-02-12 12:21 UTC, matthewdking commented on src/components/App.js
> +const app = () => (
app -> `App`

2018-02-12 12:21 UTC, matthewdking commented on src/components/ListButtons.js
> +      //handleRedirct to obj.link;
does this need to be left for another PR?

2018-02-12 12:23 UTC, matthewdking commented on public/main.css
> +.div-introduction{
also I would add a css reset or just add this to the body
```
margin: 0;
```

2018-02-13 15:11 UTC, matthewdking commented
@hasansaad1 any progress with this?

2018-02-14 13:54 UTC, Karyum commented
@hasansaad1 this PR is for #18 not chart 1 #8 if you want to keep chart 1 this PR will **Never ever pass** me and @matthewdking will 100% definitely will not approve this.
@ghassanmas @hasansaad1 @prodionov your github workflow is just at the bottom of the charts while everyone else ( yes im comparing you to the rest of the cohort ) has excellent github workflow whats the difference between you and the other teams ? thats what i want to know.

2018-02-14 15:04 UTC, hasansaad1 commented
PR relate to issue #18

2018-02-15 16:04 UTC, prodionov approved these changes

2018-02-15 16:20 UTC, matthewdking approved these changes
APPPROVED :taco:

2018-02-15 16:20 UTC, merged